// Icons come back as SVG markup generated by a model, so we treat them as
// untrusted input in two layers:
//
// 1. `stripDangerousServer` runs in the API route (Node has no DOMParser),
//    as a cheap defense-in-depth pass — remove script tags, event handler
//    attributes, and javascript: URIs before the markup ever leaves the
//    server.
// 2. `sanitizeIconMarkup` runs in the browser before rendering, and is the
//    real authority: it parses the markup and rebuilds it from a strict
//    whitelist of shape tags/attributes, dropping everything else.

const ALLOWED_TAGS = ['circle', 'rect', 'line', 'ellipse', 'polygon', 'polyline', 'path', 'g'];
const ALLOWED_ATTRS = [
  'cx', 'cy', 'r', 'rx', 'ry', 'x', 'y', 'width', 'height',
  'x1', 'y1', 'x2', 'y2', 'points', 'd',
  'stroke', 'fill', 'stroke-width', 'stroke-linecap', 'stroke-linejoin', 'transform',
];

export function stripDangerousServer(raw: string): string {
  if (!raw) return '';
  return raw
    .replace(/<script[\s\S]*?<\/script>/gi, '')
    .replace(/on\w+\s*=\s*"[^"]*"/gi, '')
    .replace(/on\w+\s*=\s*'[^']*'/gi, '')
    .replace(/javascript:/gi, '')
    .replace(/<(?!\/?(?:circle|rect|line|ellipse|polygon|polyline|path|g)\b)[^>]*>/gi, '');
}

export function sanitizeIconMarkup(raw: string): string {
  if (!raw || typeof window === 'undefined') return '';
  try {
    const doc = new DOMParser().parseFromString(
      `<svg xmlns="http://www.w3.org/2000/svg">${raw}</svg>`,
      'image/svg+xml'
    );
    if (doc.querySelector('parsererror')) return '';

    const clean = (node: Element) => {
      [...node.children].forEach((child) => {
        if (!ALLOWED_TAGS.includes(child.tagName.toLowerCase())) {
          child.remove();
          return;
        }
        [...child.attributes].forEach((attr) => {
          if (!ALLOWED_ATTRS.includes(attr.name.toLowerCase())) {
            child.removeAttribute(attr.name);
          }
        });
        clean(child);
      });
    };
    clean(doc.documentElement);
    return doc.documentElement.innerHTML;
  } catch {
    return '';
  }
}
